/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gato;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    /**E
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cons = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        selec = new javax.swing.JLabel();
        gatoCon = new javax.swing.JButton();
        graf = new javax.swing.JLabel();
        gatoGra = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cons.setFont(new java.awt.Font("Gill Sans MT", 2, 24)); // NOI18N
        cons.setForeground(new java.awt.Color(255, 255, 255));
        cons.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CONSOLA.PNG"))); // NOI18N
        cons.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(cons, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, -1));

        titulo.setFont(new java.awt.Font("Gill Sans MT", 2, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("¡BIENVENIDO AL JUEGO DEL GATO!");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 350, 40));

        selec.setFont(new java.awt.Font("Gill Sans MT", 2, 24)); // NOI18N
        selec.setForeground(new java.awt.Color(255, 255, 255));
        selec.setText("Seleccione la plataforma del juego");
        getContentPane().add(selec, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 350, 40));

        gatoCon.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        gatoCon.setText("Consola");
        gatoCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatoConActionPerformed(evt);
            }
        });
        getContentPane().add(gatoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        graf.setFont(new java.awt.Font("Gill Sans MT", 2, 24)); // NOI18N
        graf.setForeground(new java.awt.Color(255, 255, 255));
        graf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/a.png"))); // NOI18N
        graf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(graf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 80, 90));

        gatoGra.setFont(new java.awt.Font("Gill Sans MT", 2, 18)); // NOI18N
        gatoGra.setText("Grafico");
        gatoGra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatoGraActionPerformed(evt);
            }
        });
        getContentPane().add(gatoGra, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gatoConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatoConActionPerformed
        this.setExtendedState(ICONIFIED);
        JuegoGato Objeto = new JuegoGato();
     	Objeto.jugarGato();
       
    }//GEN-LAST:event_gatoConActionPerformed

    private void gatoGraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatoGraActionPerformed
         this.setExtendedState(ICONIFIED);
         
          java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new GatoInt().setVisible(true);
            }
        });
    }//GEN-LAST:event_gatoGraActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);  
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cons;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton gatoCon;
    private javax.swing.JButton gatoGra;
    private javax.swing.JLabel graf;
    private javax.swing.JButton salir;
    private javax.swing.JLabel selec;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
